"""Which generation of a schema corpus a result was measured against.

Both schema corpora are generated artefacts that live outside this repository,
and neither is something a fresh clone gets. A run records a hash per document
and, without this, nothing about the set those documents were drawn from: two
people could run the same grid against two generations and compare the answers
without noticing.

So a module is named, pinned by a digest, and fetched:

    >>> directory = fetch_module(QUANTITIES)   # doctest: +SKIP
    >>> run_the_grid(directory)                # doctest: +SKIP

The digest is the pin, not the revision. A revision says which commit was
asked for; a digest says what arrived, covers the file names as well as the
bytes, and is checkable by someone who obtained the module another way.

**Two generations of the quantity module are not interchangeable.** Measured
2026-10-04 against the published `oold-reference-schemas` branch: 234 of 942
kinds carry case-folded unit identifiers there, ``celsius_per_hour`` against
``Celsius_per_hour``, ``ha`` against ``Ha``, ``ph_value`` against ``pH_value``.
The fold is injective, 1,291 distinct identifiers on both sides and no kind
loses a unit, so neither vocabulary is wrong. They are different, and a model
answering ``Ha`` is right against one and wrong against the other. Every
quantity number this benchmark reports was measured against the case-preserving
generation, which is the one :data:`QUANTITIES` names.

The schema.org module has no such split. The published form adds
``x-oold-uuid`` and ``x-oold-version`` and rewrites ``$id`` and ``$schema``,
none of which a loader here reads, and both sources yield 906 classes, 122
describable, 62 linkable and byte-identical task records.
"""

from __future__ import annotations

import hashlib
import os
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "QUANTITIES",
    "SCHEMAORG",
    "SCHEMAS_ENV",
    "CorpusDigest",
    "Module",
    "corpus_digest",
    "fetch_module",
    "resolve_module",
]

SCHEMAS_ENV = "OOLD_BENCH_SCHEMAS"
"""Points at an already-obtained module, and is still digest-checked."""


@dataclass(frozen=True)
class Module:
    """A published schema corpus, and what it must hash to."""

    name: str
    repo_id: str
    """A Hugging Face dataset repository, which serves a directory of files at
    a revision without the caller cloning nine other modules to reach one."""
    subdirectory: str
    digest: str
    files: int
    revision: str = "main"

    def describe(self) -> dict[str, object]:
        return {"module": self.name, "repo": self.repo_id, "revision": self.revision, "digest": self.digest}


QUANTITIES = Module(
    name="quantities-qudt",
    repo_id="OO-LD/oold-quantity-schemas",
    subdirectory="schemas",
    digest="105d1bbe2e08140a33593201e8cffec5caa4026f32c1968c9cc9957038deacf6",
    files=944,
)
"""943 quantity kinds from QUDT, with case-preserving unit identifiers.

The generation every quantity figure was measured against. The 944th file is
``QuantityValue``, the base the kinds narrow.
"""

SCHEMAORG = Module(
    name="schemaorg",
    repo_id="OO-LD/oold-schemaorg-schemas",
    subdirectory="schemas",
    digest="bcf25cf6f40dfc94e43b40a959b7a7b0aa1e44747619040e68aa5003b90ebd26",
    files=920,
)
"""919 schema.org classes, of which the loader reads 906.

Byte-identical in task records to a local generation, so this one is a
convenience rather than a pin on a particular vocabulary.
"""

_CHUNK = 1 << 16


class CorpusDigest(str):
    """A digest that carries how many files it covered.

    A bare hash cannot tell a corpus that moved from a corpus that half
    arrived, and half-arriving is the likelier accident when the directory is
    generated by a separate tool.
    """

    files: int

    def __new__(cls, digest: str, files: int) -> CorpusDigest:
        self = super().__new__(cls, digest)
        self.files = files
        return self

    def describe(self) -> dict[str, object]:
        return {"digest": str(self), "files": self.files}


def corpus_digest(directory: Path, pattern: str = "*.json") -> CorpusDigest:
    """Hash a corpus directory, name and content, in a fixed order.

    Sorted by name so a filesystem's ordering never enters the result, and the
    name is hashed beside the bytes so renaming a schema is a change. Read in
    chunks because the schema.org corpus is a few thousand files.
    """
    paths = sorted(p for p in directory.glob(pattern) if p.is_file())
    if not paths:
        raise ValueError(f"{directory} holds no {pattern}, so there is nothing to digest")
    return CorpusDigest(_digest_of(paths), len(paths))


def verify(directory: Path, module: Module) -> CorpusDigest:
    """Refuse a directory that is not the module it claims to be.

    The message names the digest found, because the likeliest reason to see it
    is a module that moved on purpose, and the next step is to pin the new one.
    """
    found = corpus_digest(directory)
    if found != module.digest:
        raise ValueError(
            f"{directory} is not {module.name}: expected {module.digest} over {module.files} files, "
            f"found {found} over {found.files}. Answers measured against the two are not comparable."
        )
    return found


def fetch_module(module: Module, dest: Path | None = None) -> Path:
    """Download a module and check it arrived whole.

    Needs the ``corpora`` extra. A benchmark that only rescores published
    records has no reason to carry a Hub client, so the import is here rather
    than at the top of the module.
    """
    try:
        from huggingface_hub import snapshot_download
    except ImportError as exc:  # pragma: no cover - exercised by the error path only
        raise ImportError(
            "fetching a schema module needs huggingface-hub: uv sync --extra corpora, "
            f"or obtain {module.repo_id} yourself and point {SCHEMAS_ENV} at it"
        ) from exc

    root = snapshot_download(
        repo_id=module.repo_id,
        repo_type="dataset",
        revision=module.revision,
        local_dir=str(dest) if dest else None,
        allow_patterns=[f"{module.subdirectory}/*"],
    )
    directory = Path(root) / module.subdirectory
    verify(directory, module)
    return directory


def resolve_module(module: Module, path: Path | None = None) -> Path:
    """The module, from wherever it already is, or fetched.

    An explicit path and :data:`SCHEMAS_ENV` are checked against the same
    digest as a download. A local generation is the normal case while a corpus
    is being built, and it is also the normal way to run a grid against a
    vocabulary nobody else has without noticing.
    """
    given = path or (Path(os.environ[SCHEMAS_ENV]) if os.environ.get(SCHEMAS_ENV) else None)
    if given is None:
        return fetch_module(module)
    verify(given, module)
    return given


def _digest_of(paths: Iterable[Path]) -> str:
    running = hashlib.sha256()
    for path in paths:
        running.update(path.name.encode("utf-8"))
        with path.open("rb") as handle:
            while chunk := handle.read(_CHUNK):
                running.update(chunk)
    return running.hexdigest()
