"""How a document points at a quantity kind without naming it.

Naming the kind in the prose turns class selection into a substring match, so
an arm given no catalogue finds the answer by reading it off the page and the
comparison between arms flattens. Four signals, of which three are real
inference:

``NAMED``
    The kind is spelled out. A ceiling condition, kept because the gap
    between it and the others measures how much of a score is lexical
    matching.
``UNIT``
    Only the value and the unit. Works for the 124 kinds whose units name no
    other kind, and for no subclass, since a subclass inherits its parent's
    units by construction.
``TRANSLATED``
    A label in another language. "Durchmesser" points at ``Diameter`` without
    an English token to match on, which is the only signal that reaches the
    505 subclasses.
``DESCRIPTION``
    QUDT's authored description of the kind, with the ones that name
    themselves filtered out.

The last two come from QUDT, not from a model. Text generated by a
model that later appears in the evaluation would let that model score against
its own phrasing, and disclosure does not remove the advantage.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from functools import lru_cache
from pathlib import Path
from typing import Any

__all__ = ["Signal", "SignalData", "Vocabulary", "load_signals"]

_DATA = Path(__file__).resolve().parent.parent / "data" / "quantity_signals.json"


class Signal(str, Enum):
    NAMED = "named"
    UNIT = "unit"
    TRANSLATED = "translated"
    DESCRIPTION = "description"
    SYNONYM = "synonym"
    """An EMMO ``altLabel``. An English synonym, which no translated label can
    be, so it separates knowing the concept from knowing another language."""
    ELUCIDATION = "elucidation"
    """An EMMO ``elucidation``, derived from ISO 80000. A second authored
    definition independent of QUDT's, so a result can be checked against a
    different phrasing of the same concept."""


class Vocabulary(str, Enum):
    """Which identifier the catalogue offers and the answer is graded against.

    ``CONSENSUS`` uses the QUDT quantity-kind name, which a model may well
    have read. ``EMMO`` uses the opaque EMMO class IRI, so ``Length`` becomes
    ``EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac``, which nothing could have
    memorised as a word.

    That is the pretraining-exposure contrast, and taking it from a real
    standard, not from a scramble, makes it an alternative vocabulary a
    community actually uses instead of an artificial obfuscation.
    """

    CONSENSUS = "consensus"
    EMMO = "emmo"
    OSW = "osw"
    """The OSW page identifier the corpus was generated from, ``OSW`` plus a
    uuid. Opaque in the same way an EMMO IRI is, and carried by every one of
    the 943 schemas, where EMMO reaches 357. That makes it the one opaque
    vocabulary available for the whole corpus."""


@dataclass(frozen=True)
class SignalData:
    """The identifying material QUDT carries for the quantity kinds."""

    labels: dict[str, dict[str, str]]
    """Kind to language tag to label, English excluded."""
    descriptions: dict[str, str]
    """Kind to an authored description that does not name the kind."""
    symbols: dict[str, str]
    synonyms: dict[str, tuple[str, ...]]
    """Kind to EMMO altLabels that do not name the kind."""
    elucidations: dict[str, str]
    """Kind to an ISO 80000 derived EMMO definition."""
    emmo_iris: dict[str, str]
    """Kind to its opaque EMMO class identifier."""
    qudt_version: str
    emmo_version: str
    source: str

    def languages_for(self, kind: str) -> tuple[str, ...]:
        return tuple(sorted(self.labels.get(kind, {})))

    def supports(self, kind: str, signal: Signal) -> bool:
        if signal is Signal.TRANSLATED:
            return bool(self.labels.get(kind))
        if signal is Signal.DESCRIPTION:
            return bool(self.descriptions.get(kind))
        if signal is Signal.SYNONYM:
            return bool(self.synonyms.get(kind))
        if signal is Signal.ELUCIDATION:
            return bool(self.elucidations.get(kind))
        return True

    def identifier(self, kind: str, vocabulary: Vocabulary) -> str | None:
        """The name this kind answers to, for the vocabularies defined here.

        ``OSW`` is resolved by the caller, because the identifier comes from
        the schema, not from QUDT or EMMO.
        """
        if vocabulary is Vocabulary.EMMO:
            return self.emmo_iris.get(kind)
        return kind

    def describe(self) -> dict[str, Any]:
        return {
            "qudt_version": self.qudt_version,
            "emmo_version": self.emmo_version,
            "source": self.source,
            "kinds_with_labels": len(self.labels),
            "kinds_with_descriptions": len(self.descriptions),
            "kinds_with_synonyms": len(self.synonyms),
            "kinds_with_elucidations": len(self.elucidations),
            "kinds_with_emmo_iri": len(self.emmo_iris),
        }


@lru_cache(maxsize=1)
def load_signals(path: Path | None = None) -> SignalData:
    """Read the committed signal data. Cached, because it never changes."""
    payload = json.loads((path or _DATA).read_text(encoding="utf-8"))
    kinds = payload["kinds"]
    return SignalData(
        labels={name: entry["labels"] for name, entry in kinds.items() if entry.get("labels")},
        descriptions={name: entry["description"] for name, entry in kinds.items() if entry.get("description")},
        symbols={name: entry["symbol"] for name, entry in kinds.items() if entry.get("symbol")},
        synonyms={
            name: tuple(entry["emmo"]["alt_labels"])
            for name, entry in kinds.items()
            if (entry.get("emmo") or {}).get("alt_labels")
        },
        elucidations={
            name: entry["emmo"]["elucidation"]
            for name, entry in kinds.items()
            if (entry.get("emmo") or {}).get("elucidation")
        },
        emmo_iris={name: entry["emmo"]["iri"] for name, entry in kinds.items() if (entry.get("emmo") or {}).get("iri")},
        qudt_version=payload["qudt_version"],
        emmo_version=payload.get("emmo_version", ""),
        source=payload["source"],
    )
